### PR TITLE
[WIP] Changed the repository architecture to be more suitable for plugins

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Please review @eduardoboucas.

@TODO: update the documentation to explain that the `dist` file does not contain any plugin. To use include-media with plugins, one has to clone the repository and update `main.scss` to import them.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
I really don't like the idea of having to clone the repo to be able to use plugins. That means having to install a whole set of tools (Gulp, LibSass + RubySass for testing, linter) just to compile a bit of Sass code to maintain media queries. I think that will put people off.

Why not simply add a separate dist file for each plugin? A considerable amount of people that use include-media are simply grabbing the `_include-media.scss` file and dumping it into their projects, so why not do the same with plugins? And if Bower is their poison, we could distribute plugins individually with Bower as well.

I just want to make sure that the library continues to be simple to use and easy to install. We should leave the tooling chain and build process for developers that want to contribute to the project, not to end users.

Also, by removing the `media-context()` functionality from the core and making it a plugin that people actively have to include, we will be breaking compatibility with v1.3.0, which is something that we fought really hard to avoid with the big refactoring.

**Comment by HugoGiraudel** [comment]
> Why not simply add a separate dist file for each plugin?

Are you suggesting have a file for core + a file per plugin (containing only the plugin)?

**Comment by eduardoboucas** [comment]
Exactly. What do you think?

**Comment by HugoGiraudel** [comment]
Sounds good. Although `media-context` should be ported out of core in 2.0.0.

**Comment by eduardoboucas** [comment]
Should we close this one then?

**Comment by HugoGiraudel** [comment]
No. I'll update it.

**Comment by eduardoboucas** [comment]
What kind of restructuring do we need to accommodate plugins? I'm even thinking that keeping each plugin in a separate repository would be a good idea, because otherwise people wouldn't be able to install them with Bower. 

We could use the README to compile a list of all the plugins and simply link out to their repositories.

**Comment by HugoGiraudel** [comment]
We need to have only two folders in `src`: `core` and `plugins`.

**Comment by HugoGiraudel** [comment]
> I'm even thinking that keeping each plugin in a separate repository would be a good idea, because otherwise people wouldn't be able to install them with Bower.

Interesting. Only if you create a *include-media* organisation then.

**Comment by eduardoboucas** [comment]
I'm torn, to be honest. While creating an organisation and having separate repositories for plugins might seem the best practice, it's probably a bit of an overkill as well. In reality, I don't foresee a huge amount plugins being created due to the nature of the language and the structure of the library — and let's face it, there's only so much you can add to a library like this.

So, going back to your previous idea of having `core` and `plugins` inside `src`, would you keep only `_include-media.scss` in the `dist` folder and then all the plugins would live inside `src`?

**Comment by HugoGiraudel** [comment]
Might be.

**Pull request closed without merging**
