### PR TITLE
Update for iPhone 6 plus

### PR DESCRIPTION
**Pull request by tanktacle**
Modified phone breakpoint to 414px, as it was leaving behind the iPhone 6 plus breakpoint

### CODE REVIEW

**Comment by robsonsobral** [comment]
This modification shouldn't be here. You should override this on your own code. That's the reason for  the `default` parameter.

**Comment by HugoGiraudel** [comment]
Unfortunately this would be quite a major change than I’m not super keen into bringing into the library. As @robsonsobral said, feel free to update this in your own code. @eduardoboucas, maybe?

**Comment by jackmcpickle** [comment]
Would break all my tests too. 😬

**Comment by robsonsobral** [comment]
The best approach is to use breakpoints on columns increments: 1 column, 2 columns, 3 columns... Leave the device breakpoints to specific cases elements, like a menu or a footer.

**Pull request closed without merging**
