### PR TITLE
Added support for an each media functionality

### PR DESCRIPTION
**Pull request by tjbenton**
I added support to allow for doing something for each media query in the list of arguments.

###### Example:
```scss
@include media("each", "breakpoint"){ // using the default breakpoints
 .#{$media}foo{
  background: black;
 }
}
```

###### Outputs:
```css
.foo{
 background: black;
}
@media (min-width: 320px){
 .phone-foo{
  background: black;
 }
}
@media (min-width: 768px){
 .tablet-foo{
  background: black;
 }
}
@media (min-width: 1024px){
 .desktop-foo{
  background: black;
 }
}
```

This type of functionality can be very useful when you are dealing with responsive design and you need to have a prefix of the breakpoint for a grid system or just have helper classes at different breakpoints.

Since this was pulled from dev it also allows support specifying the dimension

###### Example:
``` scss
@include media("each", "height>=breakpoint"){
 .#{$media}bar{
  background: red;
 }
}
```

You can see more examples here in this [gist](http://sassmeister.com/gist/5a80be99f082b09ce8b9)

### CODE REVIEW

**Comment by tjbenton** [comment]
I also wrote a helper function/mixin to add the prefix to the selector(it doesn't use the sass selector functions it does it all through strings). 

I wrote this just because I find that the code looks much cleaner when you use
```scss
@include media("each", "breakpoint"){
 @include media-prefix(foo){
  background: black;
 }
}
```
verses 
```scss
@include media("each", "breakpoint"){
 .#{$media}foo{
  background: black;
 }
}
```

```scss
// @author Tyler Benton
// @arg {string | selector} $args... - You can pass a quoted string or a excaped selector (\.foobar)
// 
// @requires $media, media-prefix()
// @description This will prepend the current media namespace to each selector in the list
//
// @markup {scss} (example="false")
//  @include media("each", "breakpoint"){
//   @include media-prefix(\.foo){
//    background: black;
//   }
//   @include media-prefix(".foo"){
//    background: black;
//   }
//   @include media-prefix(foo){
//    background: black;
//   }
//  }
//  
// @markup {scss} (example="false")
//  @include media("each", "breakpoint"){
//   @include media-prefix(foo, bar, baz){
//    background: black;
//   }
//  }
@mixin media-prefix($args...){
 $selector: "";
 @each $arg in $args{
  $selector: $selector + media-prefix($arg);
 }
 #{$selector}{
  @content;
 }
}

@if not variable-exists(media){ // just ensures $media is defined
 $media: "" !global;
}

@function media-prefix($selector){
 $selector: unquote(inspect(unquote($selector)));
 $first-char: str-slice($selector, 1, 1);
 @if $first-char == "\\"{
  @return media-prefix(str-slice($selector, 2));
 }@else if $first-char == "."{
  @return str-insert($selector, $media, 2);
 }@else{
  @return unquote("." + $media + $selector);
 }
}
```

**Comment by eduardoboucas** [comment]
First of all, sorry for the delay in this response. I was hoping to have some feedback from other people before sharing my own views. In any case, here's what I think:

> This type of functionality can be very useful when you are dealing with responsive design and you need to have a prefix of the breakpoint for a grid system or just have helper classes at different breakpoints.

I honestly never had the need to use something like this. Unless I'm missing something really trivial here, having a class for each breakpoint seems a bit redundant. Who would add or remove this class? JavaScript? 

In any case, if only "tablets" will ever get the `.tablet-foo` class, why not just have those rules inside a simple media query? I think this can lead to very confusing code.

But more importantly, I would be more than happy to merge this if it adds value to the library without compromising its simplicity, which I honestly don't think is the case. It adds a lot of code and complexity and, to me, compromises the main principle of having a very natural and intuitive (almost verbal) syntax. 

To me, `@include media("each", "" ,">=phone", "<=tablet"){}` doesn't feel natural at all. Just by looking at it, I don't understand what it's supposed to do.

Consequently, given that the benefits aren't dead obvious and that this feature would add considerable complexity to the library, I don't think it's a good idea to merge this in. But thanks for putting the time and definitely keep us posted if you're using this in your fork and how people are responding to it.

**Comment by tjbenton** [comment]
Most of the changes that you see are just because I updated the formatting and converted single quotes to double quotes to match my companies standards because I'm using it in a project. 

I only added 1 if statement lines 109-132, and a variable reset on line 107. Other than adding a few examples I don't think I touched anything else. 

I realize that this type of feature isn't something that would be used alot, and I wouldn't recommend using it everywhere because it does create redundant code. That being said I use it very sparingly. 
 1. I use it for sass silent selectors (`%#{$media}clear`) so I can take advantage of the sass `@extend` feature and since you *can't* use `@extend` outside of the current scope(aka - can't extend unless it's in the same media query) this feature becomes invaluable because it allows you to use `@extend` in any scope. I use this technique combined with mixins like the good ol' clear fix. Here is an [article](http://hugogiraudel.com/2014/03/31/getting-the-most-out-of-sass-placeholders/) written by @HugoGiraudel  showcasing this type of technique and you can see how this is a way to fix the cross-scope extending issues that have been raised by several people in these issues [#501](https://github.com/nex3/sass/issues/501), [#640](https://github.com/nex3/sass/issues/640), [#915](https://github.com/nex3/sass/issues/915), [#1050](https://github.com/nex3/sass/issues/1050), [#1083](https://github.com/nex3/sass/issues/1083).
 2. I also use it for utilitie classes because you might need to show and hide things at different screen sizes, or you might want the text to be aligned centered on mobile and aligned left on tablet. All without having to add another media query just to do a simple task. 
  ```scss
  @include media("each", "breakpoint"){
   .#{$media}show{
    display: block !important;
   }
   .#{$media}hide{
    display: none !important;
   }
   .#{$media}hide, .#{$media}invisible{
    visibility: hidden !important;
   }
   .#{$media}show, .#{$media}visible{
    visibility: visible !important;
   }

   // .. other utilitie classes
  }
  ```
 3. The only other time that I use it is when building a grid system which is a very common thing todo.


I have found this type of feature to be invaluable on large scale projects where you're working with multiple developers because it actually reduces the amount of declarations that are used in each of the breakpoints where they're just wanting to show/hide, realign some text, etc. Again this feature isn't something that would be used throughout your sass code base but it does come in very handy. 

I understand how `@include media("each", "" ,">=phone"){}` may not be 100% clear so you could change the `""` to be `"base"`, `"none"`, or something else. I went with `""` because to me it indicated that you just wanted the base class without a media query prefix.

**Comment by eduardoboucas** [comment]
I'll reopen this so we can hopefully have more people giving feedback. Regarding the rest of your changes, we won't change single quotes to double since we're following @HugoGiraudel's [Sass Guidelines](http://sass-guidelin.es).

**Comment by tjbenton** [comment]
That sounds good, I just had to change them to pass code review where I work.

**Comment by HugoGiraudel** [comment]
> Regarding the rest of your changes, we won't change single quotes to double since we're following @HugoGiraudel's Sass Guidelines.

And that means a lot to me. :)

**Comment by HugoGiraudel** [comment]
I'm catching up on this. That sounds like an awful lot of complexity to me. There are things that are better staying as an external project-specific plugin rather than being merged into the core lib. This is how you end up having ugly behemoth projects to work with.

As clever as it might be, I'd say no. Now of course, that's not my lib so @eduardoboucas, do as you wish. :)

**Comment by eduardoboucas** [comment]
I'm going to close this because of the excessive complexity it adds to the library, whilst we're currently in the process of simplifying things as much as possible. I like the idea of having plugins that extend the functionality of the core, so this is probably a good case for that. Feel free to explore that approach and I'll be happy to link to it in the README or in a future plugins section.

Thanks!

**Comment by HugoGiraudel** [comment]
Update: since the code base has been dramatically updated, the PR is now irrelevant.

**Pull request closed without merging**
