### PR TITLE
[RFR] Improved package.json and added a configuration file for SassDoc

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Also be sure to re-build the docs after merging. :)

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Cheers @HugoGiraudel!

**Comment by eduardoboucas** [comment]
Cheers @HugoGiraudel!

Before merging this in, let me ask you a question about SassDoc. What's the best way to add the config maps (`$breakpoints`, `$media-expressions` and `$unit-intervals`) to the documentation? It only seems to be picking up mixins and functions.

**Comment by HugoGiraudel** [comment]
Well, `$unit-intervals` has no documentation so it makes sense that it's not being documented. The first one uses `@name` while it's not supported yet, so that might be it. Regarding the second one, it looks fine so I'm puzzled.

What SassDoc version do you use (`--version`)? How do you run SassDoc? Can you please run it in verbose and show me the result (`--verbose`)?

**Comment by eduardoboucas** [comment]
Yeah, I was trying different things that's why you see those inconsistencies.

I'm running SassDoc 2.0.0 and this is what I get with `--verbose` and `--debug`:

```
Eduardos-MBP:include-media eduardoboucas$ sassdoc dist/ --dest ../include-media.com/documentation/ --verbose --debug
» [DEBUG] argv: ["dist/","--dest","../include-media.com/documentation/","--verbose","--debug"] 
» [DEBUG] process.argv: ["node","/usr/local/bin/sassdoc","dist/","--dest","../include-media.com/documentation/","--verbose","--debug"] 
» [DEBUG] sassdoc version: 2.0.0 
» [DEBUG] node version: 0.10.36 
» [DEBUG] npm version: 1.4.28 
» [DEBUG] platform: darwin 
» [DEBUG] cwd: /Users/eduardoboucas/Sites/include-media 
» [DEBUG] env: {
  "strict": false,
  "file": ".sassdocrc",
  "dest": "../include-media.com/documentation/",
  "dir": "/Users/eduardoboucas/Sites/include-media",
  "package": {},
  "themeName": "default",
  "src": [
    "dist/"
  ]
} 
» [DEBUG] task: callee$1$0 
» [WARNING] Parser for annotation `name` not found. Location: `_include-media.scss:14:21`
» Folder `dist/` successfully parsed.
» [DEBUG] Dumping data to `sassdoc-data.json`. 
» Folder `../include-media.com/documentation/` successfully refreshed.
» Theme `default` successfully rendered.
» Process over. Everything okay!
✓ SassDoc completed after 235ms
Eduardos-MBP:include-media eduardoboucas$ 
```

**Comment by HugoGiraudel** [comment]
Ping @valeriangalliat @pascalduez @fweinb.

**Comment by valeriangalliat** [comment]
`$breakpoints` and `$media-expressions` are rendered for me, SassDoc 2.0.0 on GNU/Linux, same Node.js and npm version as you.

**Comment by eduardoboucas** [comment]
It's working now, randomly. Thanks @HugoGiraudel and @valeriangalliat!

**Pull request merged**
