### PR TITLE
Add 2 output configurations

### PR DESCRIPTION
**Pull request by JulienCabanes**

### CODE REVIEW

**Comment by eduardoboucas** [comment]
It would be useful to add a bit of information to the pull request so people can know what it's about and give an opinion.

For now, here's the [conversation on Twitter](https://twitter.com/Zee_Labs/status/563053156255670272).

**Comment by blackfalcon** [comment]
It's an idea that I can see some value in, especially if you are exporting an IE8 specific stylesheet, no need to include all the things that the browser will ignore anyway. 

My concern is that this appears to set the flag at a global level? So if I were to set it to `false` just before including the mixin, then this would be true for the rest of the style sheet and then I would have reset back to `true` again later. That's not cool. Per that example, why would I even use the mixin?

Then using your code in SassMeister I did the following per how I see you would have to do this?

```
.block {
  width: 100%;
  @include media(">phone") {
    width: 650px;
  }
}

$media-query-support: false;
.block {
  width: 100%;
  @include media(">phone") {
    width: 650px;
  }
}

$media-query-support: true;
.block {
  width: 100%;
  @include media(">phone") {
    width: 650px;
  }
}
```

which output 

```
.block {
  width: 100%; }
  @media (min-width: 321px) {
    .block {
      width: 650px; } }

.block {
  width: 100%;
  width: 650px; }

.block {
  width: 100%; }
  @media (min-width: 321px) {
    .block {
      width: 650px; } }
```

Given a typical mobile first strategy where you would set the initial values for an element to be 'mobile' and then use breakpoints on the way up, so that's not going to work. 

What's interesting with Sass' updates to how the global variable will work, the following code won't work:

```
.alpha {
  width: 100%;
  @include media(">phone") {
    width: 650px;
  }
}

.bravo {
  width: 100%;
  $media-query-support: false;
  @include media(">phone") {
    width: 650px;
  }
}

.charlie {
  width: 100%;
  @include media(">phone") {
    width: 650px;
  }
}
```

It simply ignores the flag option within the scope of the selector. Libsass on the other hand, since it doesn't yet support the new variable uses, will output this in the CSS, note that this is the same output you would get if the line above had the `!global` flag in it. 

```
.alpha {
  width: 100%; }
  @media (min-width: 321px) {
    .alpha {
      width: 650px; } }

.bravo {
  width: 100%;
  width: 650px; }

.charlie {
  width: 100%;
  width: 650px; }
```

Again, this doesn't work, unless I do the following which I find not a really solid option:

```
.alpha {
  width: 100%;
  @include media(">phone") {
    width: 650px;
  }
}

.bravo {
  width: 100%;
  $media-query-support: false;
  @include media(">phone") {
    width: 650px;
  }
}

.charlie {
  width: 100%;
  $media-query-support: true;
  @include media(">phone") {
    width: 650px;
  }
}
```


Like I said, I like this idea of supporting this. I don't think that this PR is the best option for this functionality. I would like to see something more as an option in the mixin itself, but that presents a challenge because of the `...` nature of the argument. You would have to set this flag first and then the Sass would be like this:

```
.alpha {
  width: 100%;
  @include media(true, ">phone") {
    width: 650px;
  }
}

.bravo {
  width: 100%;
  @include media(false, ">phone") {
    width: 650px;
  }
}

.charlie {
  width: 100%;
  @include media(true, ">phone") {
    width: 650px;
  }
}
```

And that just feels awkward, but less awkward then:

```
.bravo {
  width: 100%;
  @include media($conditions: ">phone") {
    width: 650px;
  }
}
```

#backtothedrawingboard

**Comment by eduardoboucas** [comment]
I'm going to close this because of the excessive complexity it adds to the library, whilst we're currently in the process of simplifying things as much as possible. I like the idea of having plugins that extend the functionality of the core, so this is probably a good case for that. Feel free to explore that approach and I'll be happy to link to it in the README or in a future plugins section.

Thanks!

**Comment by eduardoboucas** [comment]
Added in #83. More info [here](http://include-media.com/documentation/#variable-im-media-support).

**Pull request closed without merging**
