### PR TITLE
Fix Dart Sass deprecation warning - global built-in function str-leng…

### PR DESCRIPTION
**Pull request by posttoast**
Fix Dart Sass deprecation warning - global built-in function str-length and str-slice are deprecated, changed to string.length and string.slice.

### CODE REVIEW

**Comment by jackmcpickle** [comment]
Thanks @posttoast , but you will need to change in the src too `src/helpers/_trim.scss`

**Comment by jackmcpickle** [comment]
Note I've just pushed a change to master to update the sass package and fix warnings in the tests. If you want to rebase

**Comment by posttoast** [comment]
Thanks, I updated the pull request :)

**Comment by jackmcpickle** [comment]
Issue with the github node runner atm. https://github.com/npm/cli/issues/7814 - but looks good will merge.

**Comment by jackmcpickle** [comment]
Thanks for picking up @posttoast

**Pull request merged**
