### PR TITLE
add yarn.lock file

### PR DESCRIPTION
**Pull request by jackmcpickle**

### CODE REVIEW

**Comment by eduardoboucas** [comment]
I must confess my knowledge about Yarn is somewhat limited. Can you provide a quick overview of the advantages of having this and what will be required for maintaining it?

Thanks!

**Comment by jackmcpickle** [comment]
You can read more here. https://yarnpkg.com/
And offical anouncement here - https://code.facebook.com/posts/1840075619545360

But in a netshell - is a replacement for npm, but faster and creates a yarn.lock with will always give you the correct version then. 

You can install with brew or npm. 

This page compares the cli commands for yarn and npm. 
https://yarnpkg.com/en/docs/migrating-from-npm

**Comment by eduardoboucas** [comment]
From what I can see [here](https://yarnpkg.com/en/docs/publishing-a-package), we'd just have to run `yarn publish` every time we want to release a new version. Is that correct?

**Comment by jackmcpickle** [comment]
Correct. same as npm there.

**Comment by eduardoboucas** [comment]
That's cool, thanks!

Do we get @HugoGiraudel's stamp of approval?

**Comment by HugoGiraudel** [comment]
Sure.

**Comment by eduardoboucas** [comment]
Merged! Thanks @jackmcpickle. 🏆

**Pull request merged**
