### PR TITLE
add namespaced build

### PR DESCRIPTION
**Pull request by gilbox**
#32

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Sounds good.

**Comment by eduardoboucas** [comment]
I already created a PR for this in #94. It's basically the same thing, but it also prefixes `media-context()`.

**Comment by eduardoboucas** [comment]
Happy to go with this one though, if you guys prefer the `eb-` prefix. `eb` is cool. :sunglasses:

**Comment by gilbox** [comment]
ah yeah yours is better, didn't see that! I was just guessing at the prefix ¯\_(ツ)_/¯

**Comment by gilbox** [comment]
go with pr #94

**Pull request closed without merging**
