### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tszarzynski**
Added link to include-media-grid in Plugins section.

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Thanks. :)

**Comment by tszarzynski** [comment]
No worries. Hope someone finds it useful... ;)

**Comment by eduardoboucas** [comment]
Nice one @tszarzynski, thanks!

**Comment by jackmcpickle** [comment]
Cool. Do you have any examples in use?

**Comment by tszarzynski** [comment]
I included few examples in README file.

I don't have any live examples at the moment as I created this plugin for the project i'm currently working on. I cannot share it a this stage unfortunately.

I'll try to add some soon though.

If you have questions about any specific use cases I'm happy to help.

**Pull request merged**
