### PR TITLE
Allow OR operator for media queries

### PR DESCRIPTION
**Pull request by jackmcpickle**
Ok its late but here is a WIP PR or addressing https://github.com/eduardoboucas/include-media/issues/102

Not the nicest solution, but a starting point - Doesn't really fit the guideline `Simplicity is a keyword in include-media, try not to involve too much complexity.` But open to suggestions and comments.

Use can see [example gist](https://gist.github.com/jackmcpickle/551cb317013e10530db9284dae645f3e) here.

### CODE REVIEW

**Comment by jackmcpickle** [comment]
Input is 
```scss
@include media('>phone', 'OR', '<tablet') {
  .red {
    color: red;
  }
}

@include media('>phone', 'OR', '<tablet', 'screen') {
  .red {
    color: red;
  }
}
```

Output
```css
@media (min-width: 321px), (max-width: 767px) {
  .red {
    color: red;
  }
}

@media screen and (min-width: 321px), screen and (max-width: 767px) {
  .red {
    color: red;
  }
}
```

**Comment by Nirazul** [comment]
Why does `'screen'` belong to both conditions? I'd expect it to count towards `'<tablet'`.

Additonally, does your implementation support more than one `OR` condition? From looking at the changes, it doesn't seem so. But I'm not sure. I think that any implementation should support an arbitrary number of `OR` statements.

Generally, I still don't really like the `or` syntax. I'd prefer something like, but this decision is up to the authors:

```
@include media('>phone' 'screen', '<tablet' 'screen') {
    .red {
        color: red;
    }
}
```

**Comment by jackmcpickle** [comment]
@Nirazul this is just how sass works by default. See [this gist](https://gist.github.com/jackmcpickle/5779662d66e8ad7eb06565dd1b88122b) 

any nested media query is added as an AND query. 

Also while I agree that the syntax you suggest is better, this would be a big breaking change to include-media. And perhaps harder due to the nature of sass lists - both `$list: one two;` and `$list: one, two;` are lists.

**Comment by Nirazul** [comment]
@jackmcpickle 
Your gist shows nested media queries. I'm talking about your example:

```
@include media('>phone', 'OR', '<tablet', 'screen') { /* <-- this 'screen' is applied to both */
  .red {
    color: red;
  }
}
```

**Comment by jackmcpickle** [comment]
@Nirazul `screen` is applied to both due to way include media processes the query list. Each item in the list is nested under the next except for now in the case of the OR. 

But agreed maybe a `media-or` mixin is the right approach. Perhaps if @eduardoboucas and @HugoGiraudel could share their vision on where the right approach should be.

**Comment by eduardoboucas** [comment]
Ideally, I'd want a syntax like:

```scss
@include media(('>medium', '<large'), ('>large', 'retina2x')) {}
```

Which targets anything between `medium` and `large` **OR** anything larger than `large` matching a `retina2x` expression. So effectively we'd be supplying multiple instances of the syntax we're already using.

I looked into this myself not too long ago and I parked it because I couldn't find a solution that wasn't ridiculously complex and backwards-compatible.

**Comment by Nirazul** [comment]
Maybe I'll find some time to prepare a PR showing this behaviour.

**Comment by jackmcpickle** [comment]
Sounds good to me. @eduardoboucas feel free to close.

**Comment by eduardoboucas** [comment]
I'll leave it open for now. Your approach is perfectly valid, even if it ends up not being the final solution, and your effort is much appreciated.

Thanks!

**Comment by eduardoboucas** [comment]
(See #144)

**Pull request closed without merging**
